---

- name: setup dev machine
  hosts: all
  tasks:
  - name: Generate SSH keypair
    user:
      name: ubuntu
      generate_ssh_key: yes
  - name: Copy gitconfig
    copy:
      src: '../templates/gitconfig'
      dest: '/home/ubuntu/.gitconfig'
  - name: Copy screen config
    copy:
      src: '../templates/screenrc'
      dest: '/home/ubuntu/.screenrc'
